name: Release CI
on:
  push:
    branches:
      - main
    tags: ['v[0-9].[0-9].[0-9]+']
  pull_request:
    branches:
      - main

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, amd64]
        os: [linux]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Compile Binary
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-s -w"
      - name: Build Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          BINARY_FILENAME=$(go mod edit -json | jq -r .Module.Path)
          VERSION=$(echo $GITHUB_REF_NAME | sed -e "s/v//")
          tar -cvzf ${BINARY_FILENAME}_${VERSION}_${{ matrix.os }}_${{ matrix.arch }}.tar.gz ${BINARY_FILENAME}
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "*.tar.gz"